name: Lint
run-name: ${{ github.actor }} running Lint action by ${{ github.event_name }}
on:
  push:
    branches: 
      - '!main'
  pull_request:
    branches: [main]
  workflow_dispatch:

# gitHub Actions 禁用 Husky
env:
  HUSKY: 0

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
