name: Lint
run-name: ${{ github.actor }} running Lint action by ${{ github.event_name }}
on:
  push:
    branches: [devel]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
